# Header
menu:
  HOME: /
  ABOUT: /about
  PROJECTS: /projects
  ARCHIVES: /archives
  OLD VERSION: http://felipesousa.github.io/old-version-blog

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: felipz_sousa
google_plus: u/0/104290563189358000367
fb_admins: felipe.simpsons