# Header
menu:
  HOME: /
  ABOUT: /about
  PROJECTS: /projects
  ARCHIVES: /archives

rss:

# Content
excerpt_link: Read More
fancybox: true

bio_photo: images/bio-photo.jpg



# Sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: