# Header
menu:
  INICIO: /
  SOBRE: /about
  PROJETOS: /projects
  ARTIGOS: /archives
  VERSÃO ANTERIOR: http://felipesousa.github.io/oldversion/


# Content
excerpt_link: Leia mais
fancybox: true

# Sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: 60406413
favicon: /favicon.png
twitter: felipz_sousa
google_plus: u/0/+FelipeSousaDev
fb_admins: felipe.simpsons
