# Header
menu:
  INICIO: /
  SOBRE: /about
  ARTIGOS: /archives
  TALKS: /talk


# Content
excerpt_link: Leia mais
fancybox: true

# Sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-60406413-1
twitter: felipz_sousa
google_plus: u/0/+FelipeSousaDev
